import React, { useState, useRef, Component } from "react";
import IndividualInspoBlogs from '../IndividualInspoBlogs';

export default class SG extends Component {

render()
{
  return (
    <IndividualInspoBlogs heading="Style Guide and Wireframe analysis" link="" altText="" img="" 
    p1={`My wireframes are in black and white, because I wanted to minimize my use of colour, so that when I did use colour it would make those elements pop off the page. The theme of my website is cottage core, I chose this theme because I wanted to encourage the player to feel relaxed and like they have visited a place in which they can be creative with no repercussions or consequences.`}
   p2={`I increased the size of my colour pallete from my last submission, yet I still kept it minimalist. For this submission I used light-blue rgb(173, 216, 730), purple (75, 53, 118) and white. I used a white and blue for my navigation to make the individual links look like clouds. I wanted my website to convey both a cottage-core and relaxing feeling when the user interacted with it. Therefore I emphasized soft edges (border radius: 5%) and lighter colours. Lighter background had black text over it so used could easily read the text. I wanted my navigation bar to look like clouds not only because it fit in with the theme but because it also went well with the internet art I had on the homepage and design page. As both of these artworks have an interactable outside daylight area. Therefore clouds at the top of the sky matched well with the idea of the clouds in the sky of the artworks. The links in my navigation turn purple on hover (I chose purple so that the lightbulb and purple could interact as they do with the blog cards). In general Links are purple. I also made it so that when the user is on a specific page, that page turns purple, so that the user is aware on what page they are on.`}
   p3={`I used the footer to notify users when the page ended and to include my contact information in a way which was non-disruptive manner to the website’s content.  I used the navigation bar as my header so users can see when they have reached the top of the page.`}
   p4={`I only used one h1 element on each page to communicate to the user that that is where they should begin reading and that that element was the most important on the page. I also used Impact as it is a heavy weight font for all h1, h2 and h3 elements because combined with a white background commands a lot of attention. I made h1, and h2 elements uppercase, as they are mostly used for headings and therefore need to be used as markers to guide the reader’s attention. To differentiate between the headings, especially h1 and h2, I changed the font weight so that h1 stood out more. h3 was mostly used for subheading so therefore did not need to be as large. For the main text, I used Geneva as it is a Serif font therefore easier and more comfortable to read, especially when attempting to skim large columes of text.`}
   p5={`The homepage of my website contains the website title, followed by an internet artwork. I included an artwork on the first page so that the user would know what to expect as they traversed through my website. The artwork I chose, has a bunny on their house. The user can use WASD to move through the home and arrow keys to rotate the camera. I thought this artwork was fitting as the user is kind of like the bunny, traversing through their house, or in the case of the user, my website. I also included short paragraphs without a short description of what the website is about and the feelings I hope to evoke in the user as they move through the site.`}
   p6={`On the design page, I placed the rough sketches first and then the wireframes, because I wanted the user to see how the website evolved from beginning to the end product in front of them. I then placed my website inspirations detailing what aspects I liked about each website the most. The user can then also see which aspects I incorporated in my own website. And then finally I placed my design essays, with a detailed layout of my thought process when building the sight.`}
   p7={`I used a timeline in my design section because I thought it made it easier for the user to see all the pages in the order, they appear on the website. As opposed to how I presented the wireframes in my last submission, in which the user had to cycle through them (each presented on different pages) using a button. This way it is on a single web page and the user only has to scroll through them.`}
   p8={`On the theory page, I placed all the essays into blog cards. I this so that the user could easily scan all the content to find the page, they were most interested in reading. In my final, iteration I would like to add more information such as subheading’s detailing the websites content (not just the heading/ what week the essay was from, as I have now) as well as an image, to provide a visual summary. `}
   p9={`I changed the blog post design structure as I was worried that placing blog cards too close to one another may cause the page to look cluttered. However, in the next submission, I would like to implement this structure and instead use animations so that the blog post in the centre increases in size on hover, and the other blog posts are minimized. This would work as a feedback loop to notify the user which blog post they would be selecting. On Blog cards, I made sure to align the main text with the button. The blog Cards all have 3x3 alignment regardless of the actual number of blog posts, in order to maintain consistency. In general, I made use of percentages for sizing for responsive design, however, for the blog posts, on smaller screens they’ll be two cards in a row and then only a single column for mobile devices. In the future I would like to add next, previous and top buttons so that the user can cycle through the pages as opposed to return the theory page and breaking the flow of their reading process.`}
p10={`The final page is the Internet Art page, where I placed an artwork of a town where the user can ride around and look around at different angles. All the games on the page use the same user controls WASD, and arrow keys. In my next iteration, I would like to add a small container with the user controls for users who are not familiar with gaming conventions. I made sure all of the games used the same user controls to increase familiarity between the user and the system.`}
references=""
prevLink={`/im4reactrepo/UIEssay`}
topLink={`/im4reactrepo/SG`}
nextLink={`/im4reactrepo/artEssay`}
   />
  )
  }
}