import React, { useState, useRef, Component } from "react";
import IndividualInspoBlogs from '../IndividualInspoBlogs';

export default class UIEssay extends Component {

render()
{
  return (
    <IndividualInspoBlogs heading="UI/UX Critical Essay" link="" altText="" img="" 
    p1={`The theme of my internet art is Cozy, cottage core. I aim to make it place where users can come to relax and release any stress or frustration, they have through interacting with the art on the website. For this reason, I added an artwork to the homepage of the website. I did this not only because I wanted to give the user an accurate representation of what to expect when interacting with my website but also because the artwork shown is of a bunny character in their house. Via the use of WASD, the player can move around and using the arrow keys they can rotate the camera to adjust their viewpoint of the house. This ability to move through a cozy home seemed like an accurate metaphor for moving through my site. When the site loads, the user, like the bunny is placed in a room and left to explore. For the background, I used light purple and blue hues, as a non-highly saturated purple tends to be associated with creativity (verywellmind, 2023).`}    
    p2={`I kept my navigation bar static, in order to create a reference point for users navigating through my site. I also highlighted the site the user is currently on, to make it a reference point and therefore prevent the user from attempting to access the same page thinking it may contain different content. Visually, I wanted the navigation block to look like clouds. Therefore I kept the background of the website white, and then used white backgrounds for the individual links, whilst making the background of the nav element a sky-like lightblue.`}
    p3={`Throughout the website, removed hard edges and replaced them with rounded edges. I did this because cottage core is associated with being cute and relaxing and hard edges seemed out of place for a cottage core visual aesthetic. `}
    p4={`For future submissions, in terms of my Internet Art, I would like to work on adding more personal touched to my spline artwork, e.g. more animations and colour customisations. The game on my Internet Art page has a blonde Caucasian girl as the main player character which is unrelatable for anyone who is not. I , therefore would like to create personalisation options for that character as well as a saving mechanic so that that data is no lost when the user revisits the website. I also think it would be cool to add a screenshot feature so the player can take photos with the character (as in Sims).`}
    p5={`In terms of improving my website as I whole, I would like to include more animations as can be seen on the Apple.com website. Their use of animations makes the webpage more dynamic and therefore keeps the user engaged for longer. Another feature I have seen on other aspects is slightly changing background color of each section on the same webpage. This would work well on my Design page, where, I have multiple sections. I would then add links so the user could skip straight to that part they wanted to read. Dividing sections would also make it easier for the user to skim through them.`}
    p6={`In terms of technical improvements, for this submission I ended up creating a .js page for each blog post. However, I could have avoided doing this if I could have instead passed a prop via button and then loaded the same page but with the details specific to that blog post. Even though I am not sure if it is possible to do that exactly, I do think there is a way to create blog posts in a more optimal manner. In terms of improving my blog post visually, I would like to add more information to blog cards which makes them easier to identify visually, such as subheadings, an image (similar to how I created the blog cards for the Website Inspiration sections on my Design page).`}
    p7={`I also would like to prioritise usability testing and behavioural research. This would involve user interviews, anonymous surveys (as these would allow users to be honest and not just tell me what I think I would like to hear about my website). I also would like to incorporate contextual inquiry as this would allow me to identify aspects of the website which may come off as confusing or difficult for users to navigate around (Arvola, 2018). `}
    p8={`Unfortunately, I am still having an issue with my Github routing which is bringing up a 404 when I reload pages on live server. I have tried changing links and redeploying, but the issue is still persisting. I hope to have this resolved prior to the exam submission. The loading time of my internet art is very long, I would like to add a loading button so that users ar reassured that something will pop up and they are not waiting for nothing. Another bug I encountered, was not being able to get the footer to the bottom of the page, regardless of using CSS to set bottom to 0; and body with to 100vh. `}

    references={'References'}
    citation={`Design Issues, Vol. 24, No. 3, Interaction Design Research in Human-Computer Interaction (Summer, 2008), pp. 85-107 (23 pages)`}
    citation2={`Cherry, K. (2023) What does the Color Purple Mean? Available At https://www.verywellmind.com/the-color-psychology-of-purple-2795820 (Accessed 17 April 2023)`}
    />
  )
  }
}